# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'fairstarterprototype' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # Pods for fairstarterprototype

    # Required by RNFirebase
    pod 'Firebase/Core', '~> 5.3.0'

    # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
    pod 'Firebase/AdMob', '~> 5.3.0'
    pod 'Firebase/Auth', '~> 5.3.0'
    pod 'Firebase/Crash', '~> 5.3.0'
    pod 'Firebase/Database', '~> 5.3.0'
    pod 'Firebase/Functions', '~> 5.3.0'
    pod 'Firebase/DynamicLinks', '~> 5.3.0'
    pod 'Firebase/Firestore', '~> 5.3.0'
    # pod 'Firebase/Invites', '~> 5.3.0'
    pod 'Firebase/Messaging', '~> 5.3.0'
    pod 'Firebase/RemoteConfig', '~> 5.3.0'
    pod 'Firebase/Storage', '~> 5.3.0'
    pod 'Firebase/Performance', '~> 5.3.0'
    pod 'Fabric', '~> 1.7.5'
    pod 'Crashlytics', '~> 3.10.4'

    #pod 'react-native-camera', :path => '../node_modules/react-native-camera'

    #pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    # Add any other subspecs you want to use in your project
    ]
end

# Remove React from projects
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
    end
end
